library(tseries)
library(xts)
library(forecast)
attach(Pulmonary_TB_reported_cases_)
library(readr)
Pulmonary_TB_reported_cases_ <- read_csv("Pulmonary TB reported cases .csv")
tsdata<-ts(as.vector(t(Pulmonary_TB_reported_cases_[,-1])),start=c(2015,1),end=c(2021,12), frequency=12)
class(tsdata)
summary(tsdata)
min(tsdata)
max(tsdata)
plot(tsdata, main="Time series plot of Reported cases of Tuberculosis")
dtsdata<- decompose(tsdata)
plot(dtsdata)
adf.test(tsdata)
model<-auto.arima(tsdata,trace=T)
model
acf(tsdata)
pacf(tsdata)
ggtsdisplay(tsdata)
forecast(model,level=0.95,h=2*12)
plot(forecast(model))
Box.test(model$residuals,type="Ljung-Box")


tseries::kpss.test(diff.tsdata)
ndiffs(tsdata)
diff.tsdata <- diff(tsdata, difference = 1)
acf(diff.tsdata)
pacf(diff.tsdata)
fit.model<- arima(diff.tsdata, order = c(1,1,0))
fit.model
